<?xml version="1.0" encoding="utf-8" satandalone="not" ?>
<!DOCTYPE VOTTING_COL[

<!ELEMENT VOTTING_COL (FIRST_CANDIDATE, SECOND_CANDIDATE)>
<!ELEMENT FIRST_CANDIDATE (NAME, DEPARTMENT, QUANTITY_VOTE,  ZONE)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT DEPARTMENT  (#PCDATA)>
<!ATTLIST   DEPARTMENT  located (N|S) #IMPLIED>
<!ELEMENT QUANTITY_VOTE (#PCDATA)>
<!ELEMENT ZONE EMPTY>
<!ELEMENT SECOND_CANDIDATE>

]>

<VOTTING_COL>
     <FIRST_CANDIDATE >  
                 <NAME>  Petro </NAME> 
	<DEPARTMENT located="N"> Bogota.D.C</DEPARTMENT>
                 <QUANTITY_VOTE>100</QUANTITY_VOTE> 	 
	<ZONE/>
    </FIRST_CANDIDATE>  
    <SECOND_CANDIDATE>  
                 <NAME>  Rodolfo Hernandes </NAME> 
	<DEPARTMENT located="W">Choco</DEPARTMENT>
                 <QUANTITY_VOTE>20</QUANTITY_VOTE> 	 
	<ZONE/>
    </SECOND_CANDIDATE>  
</VOTTING_COL>